import { Market } from "./types";

const now = Date.now();
const day = 86400000;

export const DEMO_MARKETS: Market[] = [
  {
    id: 0,
    publicKey: "demo_0",
    question: "Will SOL reach $300 by March 2026?",
    description: "Resolves YES if SOL/USD price on Pyth oracle is >= $300 at expiry.",
    category: "Crypto",
    yesPrice: 0.62,
    noPrice: 0.38,
    volume: 48520,
    liquidity: 12000,
    expiresAt: new Date(now + 30 * day).toISOString(),
    createdAt: new Date(now - 5 * day).toISOString(),
    status: "active",
    resolutionSource: "Pyth: SOL/USD",
    resolutionValue: 300,
    resolutionOperator: 0,
    outcome: null,
    feeBps: 200,
    yesAmount: 8000,
    noAmount: 12800,
    yesMint: "demo",
    noMint: "demo",
    vault: "demo",
    collateralMint: "demo",
    authority: "demo",
  },
  {
    id: 1,
    publicKey: "demo_1",
    question: "Will BTC hit $150K by Q2 2026?",
    description: "Resolves YES if BTC/USD price on Pyth oracle is >= $150,000 at expiry.",
    category: "Crypto",
    yesPrice: 0.45,
    noPrice: 0.55,
    volume: 125000,
    liquidity: 35000,
    expiresAt: new Date(now + 90 * day).toISOString(),
    createdAt: new Date(now - 3 * day).toISOString(),
    status: "active",
    resolutionSource: "Pyth: BTC/USD",
    resolutionValue: 150000,
    resolutionOperator: 0,
    outcome: null,
    feeBps: 200,
    yesAmount: 20000,
    noAmount: 16000,
    yesMint: "demo",
    noMint: "demo",
    vault: "demo",
    collateralMint: "demo",
    authority: "demo",
  },
  {
    id: 2,
    publicKey: "demo_2",
    question: "ETH above $5,000 by April 2026?",
    description: "Resolves YES if ETH/USD price on Pyth oracle is >= $5,000 at expiry.",
    category: "Crypto",
    yesPrice: 0.38,
    noPrice: 0.62,
    volume: 67800,
    liquidity: 18000,
    expiresAt: new Date(now + 45 * day).toISOString(),
    createdAt: new Date(now - 7 * day).toISOString(),
    status: "active",
    resolutionSource: "Pyth: ETH/USD",
    resolutionValue: 5000,
    resolutionOperator: 0,
    outcome: null,
    feeBps: 200,
    yesAmount: 15000,
    noAmount: 9200,
    yesMint: "demo",
    noMint: "demo",
    vault: "demo",
    collateralMint: "demo",
    authority: "demo",
  },
  {
    id: 3,
    publicKey: "demo_3",
    question: "Will Jupiter flip Uniswap in TVL?",
    description: "Resolves YES if Jupiter DEX TVL exceeds Uniswap TVL at expiry per DefiLlama.",
    category: "DeFi",
    yesPrice: 0.22,
    noPrice: 0.78,
    volume: 31200,
    liquidity: 8500,
    expiresAt: new Date(now + 60 * day).toISOString(),
    createdAt: new Date(now - 2 * day).toISOString(),
    status: "active",
    resolutionSource: "DefiLlama TVL",
    resolutionValue: null,
    resolutionOperator: 0,
    outcome: null,
    feeBps: 200,
    yesAmount: 10000,
    noAmount: 2800,
    yesMint: "demo",
    noMint: "demo",
    vault: "demo",
    collateralMint: "demo",
    authority: "demo",
  },
  {
    id: 4,
    publicKey: "demo_4",
    question: "SOL above $200 end of February?",
    description: "Resolves YES if SOL/USD >= $200 on Feb 28, 2026 23:59 UTC.",
    category: "Crypto",
    yesPrice: 0.73,
    noPrice: 0.27,
    volume: 89400,
    liquidity: 22000,
    expiresAt: new Date(now + 12 * day).toISOString(),
    createdAt: new Date(now - 10 * day).toISOString(),
    status: "active",
    resolutionSource: "Pyth: SOL/USD",
    resolutionValue: 200,
    resolutionOperator: 0,
    outcome: null,
    feeBps: 200,
    yesAmount: 6000,
    noAmount: 16000,
    yesMint: "demo",
    noMint: "demo",
    vault: "demo",
    collateralMint: "demo",
    authority: "demo",
  },
  {
    id: 5,
    publicKey: "demo_5",
    question: "Will Solana process 100K TPS this month?",
    description: "Resolves YES if Solana mainnet achieves sustained 100K+ TPS for at least 1 hour.",
    category: "Crypto",
    yesPrice: 0.15,
    noPrice: 0.85,
    volume: 18900,
    liquidity: 5000,
    expiresAt: new Date(now + 14 * day).toISOString(),
    createdAt: new Date(now - 4 * day).toISOString(),
    status: "active",
    resolutionSource: "Solana Explorer",
    resolutionValue: null,
    resolutionOperator: 0,
    outcome: null,
    feeBps: 200,
    yesAmount: 10000,
    noAmount: 1800,
    yesMint: "demo",
    noMint: "demo",
    vault: "demo",
    collateralMint: "demo",
    authority: "demo",
  },
];
