export const IDL = {
  version: "0.1.0",
  name: "ghostodds",
  address: "FU64EotiwqACVJ9hyhH6XA9iiqQKmWjmPTUmSF1i3ar9",
  metadata: { address: "FU64EotiwqACVJ9hyhH6XA9iiqQKmWjmPTUmSF1i3ar9" },
  instructions: [
    {
      name: "initializePlatform",
      accounts: [
        { name: "platform", isMut: true, isSigner: false },
        { name: "authority", isMut: true, isSigner: true },
        { name: "treasury", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "feeBps", type: "u16" }],
    },
    {
      name: "createMarket",
      accounts: [
        { name: "platform", isMut: true, isSigner: false },
        { name: "market", isMut: true, isSigner: false },
        { name: "yesMint", isMut: true, isSigner: false },
        { name: "noMint", isMut: true, isSigner: false },
        { name: "collateralMint", isMut: false, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "authorityCollateral", isMut: true, isSigner: false },
        { name: "authority", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
        { name: "rent", isMut: false, isSigner: false },
      ],
      args: [
        { name: "question", type: "string" },
        { name: "description", type: "string" },
        { name: "category", type: "string" },
        { name: "resolutionSource", type: "string" },
        { name: "resolutionValue", type: { option: "u64" } },
        { name: "resolutionOperator", type: "u8" },
        { name: "expiresAt", type: "i64" },
        { name: "initialLiquidity", type: "u64" },
      ],
    },
    {
      name: "buyOutcome",
      accounts: [
        { name: "market", isMut: true, isSigner: false },
        { name: "platform", isMut: true, isSigner: false },
        { name: "yesMint", isMut: true, isSigner: false },
        { name: "noMint", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "treasury", isMut: true, isSigner: false },
        { name: "userCollateral", isMut: true, isSigner: false },
        { name: "userYesTokens", isMut: true, isSigner: false },
        { name: "userNoTokens", isMut: true, isSigner: false },
        { name: "userPosition", isMut: true, isSigner: false },
        { name: "user", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "amount", type: "u64" },
        { name: "isYes", type: "bool" },
        { name: "minTokensOut", type: "u64" },
      ],
    },
    {
      name: "sellOutcome",
      accounts: [
        { name: "market", isMut: true, isSigner: false },
        { name: "platform", isMut: true, isSigner: false },
        { name: "yesMint", isMut: true, isSigner: false },
        { name: "noMint", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "treasury", isMut: true, isSigner: false },
        { name: "userCollateral", isMut: true, isSigner: false },
        { name: "userYesTokens", isMut: true, isSigner: false },
        { name: "userNoTokens", isMut: true, isSigner: false },
        { name: "userPosition", isMut: true, isSigner: false },
        { name: "user", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "amount", type: "u64" },
        { name: "isYes", type: "bool" },
        { name: "minCollateralOut", type: "u64" },
      ],
    },
    {
      name: "resolveMarket",
      accounts: [
        { name: "market", isMut: true, isSigner: false },
        { name: "resolver", isMut: false, isSigner: true },
        { name: "pythPriceAccount", isMut: false, isSigner: false, isOptional: true },
      ],
      args: [{ name: "outcome", type: "bool" }],
    },
    {
      name: "redeemWinnings",
      accounts: [
        { name: "market", isMut: false, isSigner: false },
        { name: "yesMint", isMut: true, isSigner: false },
        { name: "noMint", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "userCollateral", isMut: true, isSigner: false },
        { name: "userYesTokens", isMut: true, isSigner: false },
        { name: "userNoTokens", isMut: true, isSigner: false },
        { name: "userPosition", isMut: true, isSigner: false },
        { name: "user", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "cancelMarket",
      accounts: [
        { name: "market", isMut: true, isSigner: false },
        { name: "authority", isMut: false, isSigner: true },
      ],
      args: [],
    },
    {
      name: "redeemCancelled",
      accounts: [
        { name: "market", isMut: false, isSigner: false },
        { name: "yesMint", isMut: true, isSigner: false },
        { name: "noMint", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "userCollateral", isMut: true, isSigner: false },
        { name: "userYesTokens", isMut: true, isSigner: false },
        { name: "userNoTokens", isMut: true, isSigner: false },
        { name: "user", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: "Platform",
      type: {
        kind: "struct",
        fields: [
          { name: "authority", type: "publicKey" },
          { name: "marketCount", type: "u64" },
          { name: "totalVolume", type: "u64" },
          { name: "feeBps", type: "u16" },
          { name: "treasury", type: "publicKey" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "Market",
      type: {
        kind: "struct",
        fields: [
          { name: "marketId", type: "u64" },
          { name: "authority", type: "publicKey" },
          { name: "question", type: "string" },
          { name: "description", type: "string" },
          { name: "category", type: "string" },
          { name: "collateralMint", type: "publicKey" },
          { name: "yesMint", type: "publicKey" },
          { name: "noMint", type: "publicKey" },
          { name: "vault", type: "publicKey" },
          { name: "yesAmount", type: "u64" },
          { name: "noAmount", type: "u64" },
          { name: "totalLiquidity", type: "u64" },
          { name: "volume", type: "u64" },
          { name: "resolutionSource", type: "string" },
          { name: "resolutionValue", type: { option: "u64" } },
          { name: "resolutionOperator", type: "u8" },
          { name: "createdAt", type: "i64" },
          { name: "expiresAt", type: "i64" },
          { name: "lockTime", type: "i64" },
          { name: "resolvedAt", type: { option: "i64" } },
          { name: "outcome", type: { option: "bool" } },
          { name: "status", type: "u8" },
          { name: "feeBps", type: "u16" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "UserPosition",
      type: {
        kind: "struct",
        fields: [
          { name: "user", type: "publicKey" },
          { name: "marketId", type: "u64" },
          { name: "yesTokens", type: "u64" },
          { name: "noTokens", type: "u64" },
          { name: "totalDeposited", type: "u64" },
          { name: "totalWithdrawn", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: "FeeTooHigh", msg: "Fee exceeds maximum allowed" },
    { code: 6001, name: "QuestionTooLong", msg: "Question exceeds maximum length" },
    { code: 6002, name: "DescriptionTooLong", msg: "Description exceeds maximum length" },
    { code: 6003, name: "CategoryTooLong", msg: "Category exceeds maximum length" },
    { code: 6004, name: "ResolutionSourceTooLong", msg: "Resolution source exceeds maximum length" },
    { code: 6005, name: "InvalidOperator", msg: "Invalid resolution operator" },
    { code: 6006, name: "ZeroAmount", msg: "Amount must be greater than zero" },
    { code: 6007, name: "ExpiryTooSoon", msg: "Market expiry too soon (minimum 24 hours)" },
    { code: 6008, name: "MathOverflow", msg: "Math overflow" },
    { code: 6009, name: "MarketNotActive", msg: "Market is not active" },
    { code: 6010, name: "MarketLocked", msg: "Market is locked for trading" },
    { code: 6011, name: "SlippageExceeded", msg: "Slippage tolerance exceeded" },
    { code: 6012, name: "MarketNotExpired", msg: "Market has not expired yet" },
    { code: 6013, name: "Unauthorized", msg: "Unauthorized" },
    { code: 6014, name: "MarketNotResolved", msg: "Market is not resolved" },
    { code: 6015, name: "NoWinnings", msg: "No winnings to redeem" },
    { code: 6016, name: "AlreadyResolved", msg: "Market is already resolved" },
    { code: 6017, name: "MarketNotCancelled", msg: "Market is not cancelled" },
    { code: 6018, name: "InvalidOracle", msg: "Invalid oracle account" },
    { code: 6019, name: "StalePriceData", msg: "Price data is stale" },
    { code: 6020, name: "PriceConfidenceTooWide", msg: "Price confidence interval too wide" },
    { code: 6021, name: "OracleRequired", msg: "Oracle price account required for oracle-resolved markets" },
  ],
} as const;
